### ISSUE TITLE
Boat sometimes moves off of the map when resuming game

### ISSUE THREAD

**Issue by ScanuNicco** [ScanuNicco/Boat-Race#17] opened 2019-01-12 23:11 UTC
Sometimes I pause the game and then when I resume it the boat is going at speed 3000 and everything is green

**Comment by ScanuNicco** [comment] 2019-01-13 17:20
![boat-bug](https://user-images.githubusercontent.com/30136040/51088433-7cace080-1714-11e9-9af5-c01a20faf4c3.png)

**Comment by zorbulator** [comment] 2019-01-16 19:24
This is a duplicate of "game keeps on going after it is paused". If you have any information about that bug you can comment there

**Comment by zorbulator** [comment] 2019-02-13 16:01
This still hasn't been closed

**Comment by zorbulator** [comment] 2019-02-13 16:04
oops wrong issue this one is the duplicate

**Closed as completed by zorbulator** 2019-02-13 16:04 UTC
Labels: bug, duplicate
